import { NextPage } from "next";
import Head from "next/head";

import { useSessionUser } from "@/modules/hooks/storageHooks/useSessionUser";

const Home: NextPage = () => {
  const [sessionUser, setSessionUser] = useSessionUser();
  console.log(sessionUser);
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Home;
